server:
  #port:8081
  servlet:
    encoding:
      force: true

spring:
  application:
    name: firstproject

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/mobile-dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level.org.hibernate:
    SQL: DEBUG
    orm.jdbc.bind: TRACE
